# Generated by Django 5.2.3 on 2025-06-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_editable_alter_note_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='editable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='note',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
